### PR TITLE
Fix roundtrip of mov from memory

### LINKED ISSUE #20: mov instruction fails roundtrip test
This instruction will fail the roundtrip test.
```
      mov    %rdi,0x601000:                     FAIL
```

### PR DESCRIPTION
**Pull request by langston-barrett**
Fixes #20 

This definitely fixes that test, but I'm not 100% sure that it's the _right_ fix. I'm new to reading the ISA manual and don't have a firm grasp of the instruction encoding.

I looked at the ISA manual Table 2-2, "32-Bit Addressing Forms with the ModR/M byte" to figure out that the value in this case should be `0x4`.

### CODE REVIEW

File: src/Flexdis86/Assembler.hs [hunk 1]
```diff
@@ -591,10 +591,9 @@ encodeValue v =
           Addr_64 seg Nothing Nothing _ | seg `elem` [FS, GS] -> return 0x04
           Addr_32 seg Nothing Nothing _ | seg `elem` [FS, GS] -> return 0x04
 
-          -- If there is no base and no index at all, 0x5 indicates
-          -- that ModR/M is followed by a raw displacement.
-          Addr_64 _ Nothing Nothing _ -> return 0x5
-          Addr_32 _ Nothing Nothing _ -> return 0x5
+          -- 0x4 indicates that the Mod/RM byte will be followed by a SIB
+          Addr_64 _ Nothing Nothing _ -> return 0x4
+          Addr_32 _ Nothing Nothing _ -> return 0x4
```
Comment (travitch) [inline src/Flexdis86/Assembler.hs:596]: I think I buy this case.  A value of 0x5 in R/M is used for IP-relative addressing.  That is handled in the next case (see `ripRefComponents`, so I'm not worried about this changing from 0x5 to 0x4 incorrectly.  Since this is a non-IP-relative memory reference, this makes sense (and the matching in `memRefComponents` makes sure that we are in that correct case).

Comment (travitch) [reply src/Flexdis86/Assembler.hs:596]: Actually, I have an extra question: can we try this fix with the following test case:

`mov qword ptr [rbp + 0x601000], rdi`

That is testing the Mod=0b10 case corresponding to the table entry we were trying to fix
